name: line_skip
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  flutter_riverpod: ^2.6.1
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  simple_barcode_scanner: ^0.3.0
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Gagalin
      fonts:
        - asset: assets/fonts/Gagalin-Regular.otf
