// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXkWxU1ecwoh1u2v9XRuRa5ZRm0uEmC0',
    appId: '1:362132041958:web:73b80b58b1426a64bd4b27',
    messagingSenderId: '362132041958',
    projectId: 'lineskip-20375',
    authDomain: 'lineskip-20375.firebaseapp.com',
    storageBucket: 'lineskip-20375.firebasestorage.app',
    measurementId: 'G-TLPJLWY0QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLEQgiCRPWhAbw5hVzIPgl837Y62Wg4to',
    appId: '1:362132041958:android:984a05c5f03ae348bd4b27',
    messagingSenderId: '362132041958',
    projectId: 'lineskip-20375',
    storageBucket: 'lineskip-20375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJcgrre8r087SdU-F3mwQegmjN7hMLP4',
    appId: '1:362132041958:ios:d7eb938a63fd6592bd4b27',
    messagingSenderId: '362132041958',
    projectId: 'lineskip-20375',
    storageBucket: 'lineskip-20375.firebasestorage.app',
    iosBundleId: 'com.example.lineSkip',
  );
}
